### ISSUE TITLE
Getting "MSG: Error No receipt forms available" for form no. 955

### ISSUE THREAD

**Issue by benesjan** [stitch-05/file-taxes-paraguay#3]
Before creating an issue make sure to read [common issues](https://github.com/stitch-05/file-taxes-paraguay#common-issues) first.

**Describe the bug**
Getting "MSG: Error No receipt forms available" when I run the script (see screenshot).

**Screenshots**
![image](https://github.com/stitch-05/file-taxes-paraguay/assets/13470840/3a59e887-84b6-44b1-8764-9656916c395d)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS

**Additional context**
I was debugging this a bit and the error was thrown when the script failed to find "Registro de Comprobantes - Presentación de Talón Resumen" in the response. I looked at the response and I noticed that it really is not there but "Registro de Comprobantes - Presentación de Talón" was present. I tried removing the " Resumen" and when I run it again the script seems to have succeeded:

```
jan@Jans-MacBook-Air-2 file-taxes-paraguay % ./file-taxes.sh
Checking session...
Logged in
Waiting 3s between requests...
Welcome JAN!
Checking pending forms...
Waiting 4s between requests...
Fetching menu items...
Waiting 4s between requests...
================
Tax form no. 955 needs to be filed
Preparing receipt management...
Waiting 2s between requests...
Getting access to receipt forms...
Waiting 1s between requests...
Retrieving receipt forms...
Waiting 1s between requests...
Sending tax form 241...
Waiting 1s between requests...
MSG: Success! Receipts for period 202406 filed successfully!
```

It's quite suspicious that there is "Sending tax form 241..." in the output when above it complains that tax form no. 955 needs to be filed so not sure if my modification was correct.

**Comment by kitharoidos** [comment]
I'm having exactly the same issue, also on macOS.

**Comment by mariodian** [comment]
This seems to be an issue on the website side. 

The new tax form shows as available but isn’t clickable yet. At least not for me.
![IMG_1437](https://github.com/stitch-05/file-taxes-paraguay/assets/3636406/610a5583-ed9c-47bf-8128-f8ad93f3d6b6)

Sometimes it takes time before the form is available. I’ve had an issue since the last few months. It eventually fixes itself later in each month.

**Comment by kitharoidos** [comment]
I also had this non-clickable form there, then I used the fix above to submit the 955 (or 241?) form using the modified script and now I no longer see the non-clickable form on the website.
